add healthcheck server

diff --git a/omnistrate.single-zone.yaml b/omnistrate.single-zone.yaml
--- a/omnistrate.single-zone.yaml
+++ b/omnistrate.single-zone.yaml
@@ -172,10 +172,11 @@ services:
     environment:
       - RUN_NODE=1
       - RUN_SENTINEL=1
+      - RUN_METRICS=1
+      - RUN_HEALTH_CHECK=1
       - SENTINEL_HOST=$sentinel.sys.network.externalClusterEndpoint
       - NODE_HOST=$sys.network.node.externalEndpoint
       - NODE_PORT=6379
-      - RUN_METRICS=1
       - TLS=$var.enableTLS
       - FALKORDB_PASSWORD=$var.falkordbPassword
       - ADMIN_PASSWORD=$func.random(string, 16)
@@ -194,6 +195,26 @@ services:
       gcp:
         instanceStorageType: GCP::PD_BALANCED
         instanceStorageSizeGiAPIParam: storageSize
+    x-omnistrate-actionhooks:
+      - scope: NODE
+        type: HEALTH_CHECK
+        commandTemplate: >
+          #!/bin/bash
+
+          HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
+
+          call_health_check() {
+
+            echo "Health check URL: $HEALTH_CHECK_URL"
+            curl -sf $HEALTH_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
+          call_health_check
     depends_on:
       - sentinel
 
