testing behaviour

diff --git a/omnistrate.pro.yaml b/omnistrate.pro.yaml
--- a/omnistrate.pro.yaml
+++ b/omnistrate.pro.yaml
@@ -1129,7 +1129,7 @@ services:
           #!/bin/bash
 
           HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
-
+          SENTINEL_HEALTH_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/healthcheck"
           call_health_check() {
 
             echo "Health check URL: $HEALTH_CHECK_URL"
@@ -1141,7 +1141,19 @@ services:
             fi
           }
 
+          sentinel_call_health_check() {
+
+            echo "Health check URL: $SENTINEL_HEALTH_CHECK_URL"
+            curl -sf $SENTINEL_HEALTH_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
           call_health_check
+          sentinel_call_health_check
       - scope: NODE
         type: REMOVE
         commandTemplate: >
@@ -1209,6 +1221,25 @@ services:
         modifiable: false
         required: true
         export: false
+    x-omnistrate-actionhooks:
+      - scope: NODE
+        type: HEALTH_CHECK
+        commandTemplate: >
+          #!/bin/bash
+
+          SENTINEL_HEALTH_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/healthcheck"
+          sentinel_call_health_check() {
+
+            echo "Health check URL: $SENTINEL_HEALTH_CHECK_URL"
+            curl -sf $SENTINEL_HEALTH_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
+          sentinel_call_health_check
 
   # Multi Zone
 
@@ -1613,7 +1644,7 @@ services:
           #!/bin/bash
 
           HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
-
+          SENTINEL_HEALTH_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/healthcheck"
           call_health_check() {
 
             echo "Health check URL: $HEALTH_CHECK_URL"
@@ -1625,7 +1656,19 @@ services:
             fi
           }
 
+          sentinel_call_health_check() {
+
+            echo "Health check URL: $SENTINEL_HEALTH_CHECK_URL"
+            curl -sf $SENTINEL_HEALTH_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
           call_health_check
+          sentinel_call_health_check
       - scope: NODE
         type: REMOVE
         commandTemplate: >
@@ -1692,6 +1735,25 @@ services:
         modifiable: false
         required: true
         export: false
+    x-omnistrate-actionhooks:
+      - scope: NODE
+        type: HEALTH_CHECK
+        commandTemplate: >
+          #!/bin/bash
+
+          SENTINEL_HEALTH_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/healthcheck"
+          sentinel_call_health_check() {
+
+            echo "Health check URL: $SENTINEL_HEALTH_CHECK_URL"
+            curl -sf $SENTINEL_HEALTH_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
+          sentinel_call_health_check
 
   Cluster-Single-Zone:
     x-omnistrate-mode-internal: false
@@ -1877,6 +1939,7 @@ services:
     depends_on:
       - cluster-sz
       - cluster-sz-rebalance
+    
 
   cluster-sz:
     x-omnistrate-mode-internal: true
