Separated healthcheck, readiness, startup probes

diff --git a/omnistrate.pro.yaml b/omnistrate.pro.yaml
--- a/omnistrate.pro.yaml
+++ b/omnistrate.pro.yaml
@@ -676,6 +676,68 @@ services:
       enableMultiZone: false
       enableEndpointPerReplica: true
     x-omnistrate-actionhooks:
+      - scope: NODE
+        type: STARTUP_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          STARTUP_CHECK_URL="${STARTUP_CHECK_HOST:-localhost}:${STARTUP_CHECK_PORT:-8081}/startup"
+          call_startup_check() {
+
+            echo "Startup check URL: $STARTUP_CHECK_URL"
+            curl -sf $STARTUP_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Startup check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_startup_check
+          fi
+      - scope: NODE
+        type: READINESS_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          READINESS_CHECK_URL="${READY_CHECK_HOST:-localhost}:${READY_CHECK_PORT:-8081}/readiness"
+          call_readiness_check() {
+
+            echo "Ready check URL: $READINESS_CHECK_URL"
+            curl -sf $READINESS_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Readiness check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_readiness_check
+          fi
+
+      - scope: NODE
+        type: HEALTH_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
+          call_health_check() {
+
+            echo "Health check URL: $HEALTH_CHECK_URL"
+            curl -sf $HEALTH_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+          call_health_check
+          fi
+
 
   # Single Zone
 
@@ -1093,41 +1155,115 @@ services:
       enableEndpointPerReplica: true
     x-omnistrate-actionhooks:
       - scope: NODE
-        type: HEALTH_CHECK
+        type: STARTUP_CHECK
         commandTemplate: |
           #!/bin/bash
 
-          HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
-          SENTINEL_HEALTH_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/healthcheck"
-          call_health_check() {
+          STARTUP_CHECK_URL="${STARTUP_CHECK_HOST:-localhost}:${STARTUP_CHECK_PORT:-8081}/startup"
+          SENTINEL_STARTUP_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/startup"
+          call_startup_check() {
 
-            echo "Health check URL: $HEALTH_CHECK_URL"
-            curl -sf $HEALTH_CHECK_URL
+            echo "Startup check URL: $STARTUP_CHECK_URL"
+            curl -sf $STARTUP_CHECK_URL
             
             if [ $? -ne 0 ]; then
-              echo "Health check failed"
-              exit 1
-            fi
-          }
-
-          sentinel_call_health_check() {
-
-            echo "Health check URL: $SENTINEL_HEALTH_CHECK_URL"
-            curl -sf $SENTINEL_HEALTH_CHECK_URL
-            
-            if [ $? -ne 0 ]; then
-              echo "Health check failed"
+              echo "Startup check failed"
               exit 1
             fi
           }
 
           if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
-          call_health_check
+            call_startup_check
           fi
 
+
+          sentinel_call_startup_check() {
+
+            echo "Health check URL: $SENTINEL_STARTUP_CHECK_URL"
+            curl -sf $SENTINEL_STARTUP_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
           if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]] && [[ $NODE_INDEX -le 1 ]];then
-            sentinel_call_health_check
+            sentinel_call_startup_check
           fi
+      - scope: NODE
+        type: READINESS_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          READINESS_CHECK_URL="${READY_CHECK_HOST:-localhost}:${READY_CHECK_PORT:-8081}/readiness"
+          SENTINEL_READINESS_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/readiness"
+          call_readiness_check() {
+
+            echo "Ready check URL: $READINESS_CHECK_URL"
+            curl -sf $READINESS_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Readiness check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_readiness_check
+          fi
+          
+          sentinel_call_readiness_check() {
+
+            echo "Health check URL: $SENTINEL_READINESS_CHECK_URL"
+            curl -sf $SENTINEL_READINESS_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]] && [[ $NODE_INDEX -le 1 ]];then
+            sentinel_call_readiness_check
+          fi
+      - scope: NODE
+        type: HEALTH_CHECK
+        commandTemplate: |
+           #!/bin/bash
+
+            HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
+            SENTINEL_HEALTH_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/healthcheck"
+            call_health_check() {
+
+              echo "Health check URL: $HEALTH_CHECK_URL"
+              curl -sf $HEALTH_CHECK_URL
+              
+              if [ $? -ne 0 ]; then
+                echo "Health check failed"
+                exit 1
+              fi
+            }
+
+            sentinel_call_health_check() {
+
+              echo "Health check URL: $SENTINEL_HEALTH_CHECK_URL"
+              curl -sf $SENTINEL_HEALTH_CHECK_URL
+              
+              if [ $? -ne 0 ]; then
+                echo "Health check failed"
+                exit 1
+              fi
+            }
+
+            if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_health_check
+            fi
+
+            if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]] && [[ $NODE_INDEX -le 1 ]];then
+              sentinel_call_health_check
+            fi
+          
       - scope: NODE
         type: REMOVE
         commandTemplate: |
@@ -1158,7 +1294,6 @@ services:
       - RUN_NODE=0
       - RUN_SENTINEL=1
       - RUN_METRICS=0
-      - RUN_HEALTH_CHECK=1
       - RUN_HEALTH_CHECK_SENTINEL=1
       - DEBUG=0
       - REDIS_EXPORTER_DEBUG=false
@@ -1206,6 +1341,47 @@ services:
         export: false
     x-omnistrate-actionhooks:
       - scope: NODE
+        type: STARTUP_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          STARTUP_CHECK_URL="${STARTUP_CHECK_HOST:-localhost}:${STARTUP_CHECK_PORT:-8082}/startup"
+          sentinel_call_startup_check() {
+
+            echo "Startup check URL: $STARTUP_CHECK_URL"
+            curl -sf $STARTUP_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Startup check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]];then
+            sentinel_call_startup_check
+          fi
+      - scope: NODE
+        type: READINESS_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          READINESS_CHECK_URL="${READY_CHECK_HOST:-localhost}:${READY_CHECK_PORT:-8082}/readiness"
+          sentinel_call_readiness_check() {
+
+            echo "Ready check URL: $READINESS_CHECK_URL"
+            curl -sf $READINESS_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Readiness check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]];then
+            sentinel_call_readiness_check
+          fi
+
+      - scope: NODE
         type: HEALTH_CHECK
         commandTemplate: |
           #!/bin/bash
@@ -1222,7 +1398,7 @@ services:
             fi
           }
 
-          if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]] && [[ $NODE_INDEX -le 1 ]];then
+          if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]];then
             sentinel_call_health_check
           fi
 
@@ -1643,41 +1819,115 @@ services:
       enableEndpointPerReplica: true
     x-omnistrate-actionhooks:
       - scope: NODE
-        type: HEALTH_CHECK
+        type: STARTUP_CHECK
         commandTemplate: |
           #!/bin/bash
 
-          HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
-          SENTINEL_HEALTH_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/healthcheck"
-          call_health_check() {
+          STARTUP_CHECK_URL="${STARTUP_CHECK_HOST:-localhost}:${STARTUP_CHECK_PORT:-8081}/startup"
+          SENTINEL_STARTUP_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/startup"
+          call_startup_check() {
 
-            echo "Health check URL: $HEALTH_CHECK_URL"
-            curl -sf $HEALTH_CHECK_URL
+            echo "Startup check URL: $STARTUP_CHECK_URL"
+            curl -sf $STARTUP_CHECK_URL
             
             if [ $? -ne 0 ]; then
-              echo "Health check failed"
-              exit 1
-            fi
-          }
-
-          sentinel_call_health_check() {
-
-            echo "Health check URL: $SENTINEL_HEALTH_CHECK_URL"
-            curl -sf $SENTINEL_HEALTH_CHECK_URL
-            
-            if [ $? -ne 0 ]; then
-              echo "Health check failed"
+              echo "Startup check failed"
               exit 1
             fi
           }
 
           if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
-          call_health_check
+            call_startup_check
           fi
 
+
+          sentinel_call_startup_check() {
+
+            echo "Health check URL: $SENTINEL_STARTUP_CHECK_URL"
+            curl -sf $SENTINEL_STARTUP_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
           if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]] && [[ $NODE_INDEX -le 1 ]];then
-            sentinel_call_health_check
+            sentinel_call_startup_check
           fi
+      - scope: NODE
+        type: READINESS_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          READINESS_CHECK_URL="${READY_CHECK_HOST:-localhost}:${READY_CHECK_PORT:-8081}/readiness"
+          SENTINEL_READINESS_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/readiness"
+          call_readiness_check() {
+
+            echo "Ready check URL: $READINESS_CHECK_URL"
+            curl -sf $READINESS_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Readiness check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_readiness_check
+          fi
+          
+          sentinel_call_readiness_check() {
+
+            echo "Health check URL: $SENTINEL_READINESS_CHECK_URL"
+            curl -sf $SENTINEL_READINESS_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]] && [[ $NODE_INDEX -le 1 ]];then
+            sentinel_call_readiness_check
+          fi
+      - scope: NODE
+        type: HEALTH_CHECK
+        commandTemplate: |
+           #!/bin/bash
+
+            HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
+            SENTINEL_HEALTH_CHECK_URL="${SENTINEL_HEALTH_CHECK_HOST:-localhost}:${SENTINEL_HEALTH_CHECK_PORT:-8082}/healthcheck"
+            call_health_check() {
+
+              echo "Health check URL: $HEALTH_CHECK_URL"
+              curl -sf $HEALTH_CHECK_URL
+              
+              if [ $? -ne 0 ]; then
+                echo "Health check failed"
+                exit 1
+              fi
+            }
+
+            sentinel_call_health_check() {
+
+              echo "Health check URL: $SENTINEL_HEALTH_CHECK_URL"
+              curl -sf $SENTINEL_HEALTH_CHECK_URL
+              
+              if [ $? -ne 0 ]; then
+                echo "Health check failed"
+                exit 1
+              fi
+            }
+
+            if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_health_check
+            fi
+
+            if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]] && [[ $NODE_INDEX -le 1 ]];then
+              sentinel_call_health_check
+            fi
+          
       - scope: NODE
         type: REMOVE
         commandTemplate: |
@@ -1707,7 +1957,6 @@ services:
       - RUN_NODE=0
       - RUN_SENTINEL=1
       - RUN_METRICS=0
-      - RUN_HEALTH_CHECK=1
       - RUN_HEALTH_CHECK_SENTINEL=1
       - DEBUG=0
       - REDIS_EXPORTER_DEBUG=false
@@ -1755,6 +2004,47 @@ services:
         export: false
     x-omnistrate-actionhooks:
       - scope: NODE
+        type: STARTUP_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          STARTUP_CHECK_URL="${STARTUP_CHECK_HOST:-localhost}:${STARTUP_CHECK_PORT:-8082}/startup"
+          sentinel_call_startup_check() {
+
+            echo "Startup check URL: $STARTUP_CHECK_URL"
+            curl -sf $STARTUP_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Startup check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]];then
+            sentinel_call_startup_check
+          fi
+      - scope: NODE
+        type: READINESS_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          READINESS_CHECK_URL="${READY_CHECK_HOST:-localhost}:${READY_CHECK_PORT:-8082}/readiness"
+          sentinel_call_readiness_check() {
+
+            echo "Ready check URL: $READINESS_CHECK_URL"
+            curl -sf $READINESS_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Readiness check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]];then
+            sentinel_call_readiness_check
+          fi
+          
+      - scope: NODE
         type: HEALTH_CHECK
         commandTemplate: |
           #!/bin/bash
@@ -1771,7 +2061,7 @@ services:
             fi
           }
 
-          if [[ ! -z $RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]] && [[ $NODE_INDEX -le 1 ]];then
+          if [[ ! -z RUN_HEALTH_CHECK_SENTINEL ]] && [[ $RUN_HEALTH_CHECK_SENTINEL -eq 1 ]];then
             sentinel_call_health_check
           fi
 
@@ -2027,12 +2317,52 @@ services:
       enableEndpointPerReplica: true
     x-omnistrate-actionhooks:
       - scope: NODE
+        type: STARTUP_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          STARTUP_CHECK_URL="${STARTUP_CHECK_HOST:-localhost}:${STARTUP_CHECK_PORT:-8081}/startup"
+          call_startup_check() {
+
+            echo "Startup check URL: $STARTUP_CHECK_URL"
+            curl -sf $STARTUP_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Startup check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_startup_check
+          fi
+      - scope: NODE
+        type: READINESS_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          READINESS_CHECK_URL="${READY_CHECK_HOST:-localhost}:${READY_CHECK_PORT:-8081}/readiness"
+          call_readiness_check() {
+
+            echo "Ready check URL: $READINESS_CHECK_URL"
+            curl -sf $READINESS_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Readiness check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_readiness_check
+          fi
+
+      - scope: NODE
         type: HEALTH_CHECK
         commandTemplate: |
           #!/bin/bash
 
           HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
-
           call_health_check() {
 
             echo "Health check URL: $HEALTH_CHECK_URL"
@@ -2345,12 +2675,52 @@ services:
       enableEndpointPerReplica: true
     x-omnistrate-actionhooks:
       - scope: NODE
+        type: STARTUP_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          STARTUP_CHECK_URL="${STARTUP_CHECK_HOST:-localhost}:${STARTUP_CHECK_PORT:-8081}/startup"
+          call_startup_check() {
+
+            echo "Startup check URL: $STARTUP_CHECK_URL"
+            curl -sf $STARTUP_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Startup check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_startup_check
+          fi
+      - scope: NODE
+        type: READINESS_CHECK
+        commandTemplate: |
+          #!/bin/bash
+
+          READINESS_CHECK_URL="${READY_CHECK_HOST:-localhost}:${READY_CHECK_PORT:-8081}/readiness"
+          call_readiness_check() {
+
+            echo "Ready check URL: $READINESS_CHECK_URL"
+            curl -sf $READINESS_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Readiness check failed"
+              exit 1
+            fi
+          }
+
+          if [[ ! -z RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
+            call_readiness_check
+          fi
+
+      - scope: NODE
         type: HEALTH_CHECK
         commandTemplate: |
           #!/bin/bash
 
           HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
-
           call_health_check() {
 
             echo "Health check URL: $HEALTH_CHECK_URL"
