add redis-cli to rebalance add healthcheck to rebalance

diff --git a/omnistrate.pro.yaml b/omnistrate.pro.yaml
--- a/omnistrate.pro.yaml
+++ b/omnistrate.pro.yaml
@@ -1928,6 +1928,26 @@ services:
       - NODE_HOST=$sys.network.node.externalEndpoint
       - NODE_PORT=6379
       - DEBUG=0
+    x-omnistrate-actionhooks:
+      - scope: NODE
+        type: HEALTH_CHECK
+        commandTemplate: >
+          #!/bin/bash
+
+          HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
+
+          call_health_check() {
+
+            echo "Health check URL: $HEALTH_CHECK_URL"
+            curl -sf $HEALTH_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
+          call_health_check
 
   Cluster-Multi-Zone:
     x-omnistrate-mode-internal: false
@@ -2226,3 +2246,23 @@ services:
       - NODE_HOST=$sys.network.node.externalEndpoint
       - NODE_PORT=6379
       - DEBUG=0
+    x-omnistrate-actionhooks:
+      - scope: NODE
+        type: HEALTH_CHECK
+        commandTemplate: >
+          #!/bin/bash
+
+          HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"
+
+          call_health_check() {
+
+            echo "Health check URL: $HEALTH_CHECK_URL"
+            curl -sf $HEALTH_CHECK_URL
+            
+            if [ $? -ne 0 ]; then
+              echo "Health check failed"
+              exit 1
+            fi
+          }
+
+          call_health_check
