secret seed not fixed, redeploying with static seed

diff --git a/.github/workflows/build-release-image.yaml b/.github/workflows/build-release-image.yaml
--- a/.github/workflows/build-release-image.yaml
+++ b/.github/workflows/build-release-image.yaml
@@ -90,7 +90,7 @@ jobs:
           if [[ -n "$sec" ]];then
             mkdir -p secrets || { echo "Failed to create secrets directory"; exit 1; }
             echo '{{ $var.falkordbPassword }}' > ./secrets/falkordbpassword || { echo "Failed to write falkordbpassword"; exit 1; }
-            echo '{{ $func.random(string, 16, $sys.deterministicSeedValue) }}' > ./secrets/adminpassword || { echo "Failed to write adminpassword"; exit 1; }
+            echo '{{ $func.random(string, 16, 12345) }}' > ./secrets/adminpassword || { echo "Failed to write adminpassword"; exit 1; }
           else
             echo "secrets option was not used"
             exit 0
