Refactor healthcheck config creation to use echo instead of cat for improved readability

diff --git a/.github/workflows/build-test-image.yaml b/.github/workflows/build-test-image.yaml
--- a/.github/workflows/build-test-image.yaml
+++ b/.github/workflows/build-test-image.yaml
@@ -169,13 +169,12 @@ jobs:
           export conf=$(grep '^configs' omnistrate.free.yaml)
           if [[ -n "$conf" ]];then
             mkdir -p configs || { echo "Failed to create configs directory"; exit 1; }
-            cat > ./configs/healthcheck <<'EOF'
-            skip_all=false
-            skip_liveness=false
-            skip_readiness=false
-            skip_startup=false
-            EOF
-            [ $? -eq 0 ] || { echo "Failed to write healthcheck config"; exit 1; }
+            echo """
+              skip_all=false
+              skip_liveness=false
+              skip_readiness=false
+              skip_startup=false
+            """ > ./configs/healthcheck || { echo "Failed to write healthcheck config"; exit 1; }
           else
             echo "configs option was not used"
             exit 0
