Add health check configuration support across multiple YAML files and update health check logic in Rust

diff --git a/.github/workflows/build-release-image.yaml b/.github/workflows/build-release-image.yaml
--- a/.github/workflows/build-release-image.yaml
+++ b/.github/workflows/build-release-image.yaml
@@ -124,7 +124,23 @@ jobs:
             echo "secrets option was not used"
             exit 0
           fi
-
+      
+      - name: Create Config files
+        run: |
+          export conf=$(grep '^configs' omnistrate.free.yaml)
+          if [[ -n "$conf" ]];then
+            mkdir -p configs || { echo "Failed to create configs directory"; exit 1; }
+            echo """
+              skip_all=false
+              skip_liveness=false
+              skip_readiness=false
+              skip_startup=false
+            """ > ./configs/healthcheck || { echo "Failed to write healthcheck config"; exit 1; }
+          else
+            echo "configs option was not used"
+            exit 0
+          fi
+      
       - name: Update Omnistrate plan
         if: ${{ contains(vars.OMNISTRATE_RELEASE_PLANS, matrix.plans.key) }}
         uses: ./.github/actions/update-omnistrate-plan
